export const traduccion = {
  "EN": {
    "nav-home": "Home",
    "nav-about": "About Us",
    "nav-services": "Services",
    "nav-how-it-works": "How It Works",
    "nav-testimonials": "Testimonials",
    "nav-faq": "FAQ",
    "nav-contact": "Contact",
    "WorkStation-title": "Welcome to WorkStation",
    "header-desc": "Your premier solution for seamless coworking space reservations.",
    "get-started": "Get Started",
    "about-title": "About Us",
    "who": "Who We Are",
    "who-desc": "WorkStation is a SaaS platform connecting freelancers and startups with flexible coworking spaces, simplifying bookings and management.",
    "vision": "Our Vision",
    "vision-desc": "To lead the coworking industry by providing an intuitive, efficient platform for workspace solutions.",
    "mission": "Our Mission",
    "mission-desc": "To empower professionals with accessible, high-quality coworking options through innovative technology.",
    "services-title": "Our Services",
    "srv-space-management": "Space Management",
    "srv-space-management-desc": "Easily publish and manage coworking spaces with real-time availability.",
    "srv-booking": "Booking System",
    "srv-booking-desc": "Streamlined reservations with instant confirmation for freelancers.",
    "srv-payments": "Payment Processing",
    "srv-payments-desc": "Secure and flexible payment options for all transactions.",
    "srv-profiles": "Profile Management",
    "srv-profiles-desc": "Customize your profile and preferences with ease.",
    "how-title": "How It Works",
    "step-1": "Sign Up",
    "step-1-desc": "Create an account as a freelancer or property owner.",
    "step-2": "Find a Space",
    "step-2-desc": "Browse and filter available coworking spaces.",
    "step-3": "Book & Pay",
    "step-3-desc": "Select your date, confirm, and process payment securely.",
    "testimonials-title": "What Our Users Say",
    "testimonial-1": "\"WorkStation made finding a workspace a breeze. Highly recommend!\"",
    "testimonial-1-author": "- Jane Doe, Freelancer",
    "testimonial-2": "\"Managing my coworking space has never been easier with this platform.\"",
    "testimonial-2-author": "- John Smith, Property Owner",
    "faq-title": "Frequently Asked Questions",
    "faq-q1": "What is WorkStation?",
    "faq-q1-desc": "WorkStation is a platform for booking and managing coworking spaces efficiently.",
    "faq-q2": "How do I book a space?",
    "faq-q2-desc": "Sign up, search for a space, select a date, and complete payment online.",
    "faq-q3": "Is my data secure?",
    "faq-q3-desc": "Yes, we use advanced encryption to protect your information.",
    "contact-title": "Contact Us",
    "contact-desc": "We are here to assist. Reach out for support or inquiries about WorkStation.",
    "contact-email-label": "Email",
    "contact-phone-label": "Phone",
    "form-title": "Send Message",
    "form-name": "Full Name",
    "form-email": "Email",
    "form-msg": "Your Message",
    "form-send": "Send",
    "footer-desc": "Enhancing coworking experiences through innovative technology.",
    "footer-contact": "Email: support@workstation.com | Phone: +51 970 526 672"
  },
  "ES": {
    "nav-home": "Inicio",
    "nav-about": "Sobre Nosotros",
    "nav-services": "Servicios",
    "nav-how-it-works": "¿Cómo Funciona?",
    "nav-testimonials": "Testimonios",
    "nav-faq": "Preguntas Frecuentes",
    "nav-contact": "Contacto",
    "WorkStation-title": "Bienvenido a WorkStation",
    "header-desc": "Tu solución principal para reservas de espacios de coworking sin complicaciones.",
    "get-started": "Comenzar",
    "about-title": "Sobre Nosotros",
    "who": "¿Quiénes Somos?",
    "who-desc": "WorkStation es una plataforma SaaS que conecta a freelancers y startups con espacios de coworking flexibles, simplificando reservas y gestión.",
    "vision": "Nuestra Visión",
    "vision-desc": "Liderar la industria del coworking proporcionando una plataforma intuitiva y eficiente para soluciones de espacio de trabajo.",
    "mission": "Nuestra Misión",
    "mission-desc": "Empoderar a profesionales con opciones de coworking accesibles y de alta calidad a través de tecnología innovadora.",
    "services-title": "Nuestros Servicios",
    "srv-space-management": "Gestión de Espacios",
    "srv-space-management-desc": "Publica y gestiona espacios de coworking con disponibilidad en tiempo real.",
    "srv-booking": "Sistema de Reservas",
    "srv-booking-desc": "Reservas optimizadas con confirmación instantánea para freelancers.",
    "srv-payments": "Procesamiento de Pagos",
    "srv-payments-desc": "Opciones de pago seguras y flexibles para todas las transacciones.",
    "srv-profiles": "Gestión de Perfiles",
    "srv-profiles-desc": "Personaliza tu perfil y preferencias con facilidad.",
    "how-title": "¿Cómo Funciona?",
    "step-1": "Regístrate",
    "step-1-desc": "Crea una cuenta como freelancer o propietario.",
    "step-2": "Encuentra un Espacio",
    "step-2-desc": "Explora y filtra espacios de coworking disponibles.",
    "step-3": "Reserva y Paga",
    "step-3-desc": "Selecciona tu fecha, confirma y procesa el pago de forma segura.",
    "testimonials-title": "Qué Dicen Nuestros Usuarios",
    "testimonial-1": "\"WorkStation hizo que encontrar un espacio de trabajo fuera muy fácil. ¡Altamente recomendado!\"",
    "testimonial-1-author": "- Jane Doe, Freelancer",
    "testimonial-2": "\"Gestionar mi espacio de coworking nunca había sido tan fácil con esta plataforma.\"",
    "testimonial-2-author": "- John Smith, Propietario",
    "faq-title": "Preguntas Frecuentes",
    "faq-q1": "¿Qué es WorkStation?",
    "faq-q1-desc": "WorkStation es una plataforma para reservar y gestionar espacios de coworking de manera eficiente.",
    "faq-q2": "¿Cómo reservo un espacio?",
    "faq-q2-desc": "Regístrate, busca un espacio, selecciona una fecha y completa el pago en línea.",
    "faq-q3": "¿Mis datos están seguros?",
    "faq-q3-desc": "Sí, utilizamos encriptación avanzada para proteger tu información.",
    "contact-title": "Contáctanos",
    "contact-desc": "Estamos aquí para ayudarte. Contáctanos para soporte o consultas sobre WorkStation.",
    "contact-email-label": "Correo",
    "contact-phone-label": "Teléfono",
    "form-title": "Enviar Mensaje",
    "form-name": "Nombre Completo",
    "form-email": "Correo",
    "form-msg": "Tu Mensaje",
    "form-send": "Enviar",
    "footer-desc": "Mejorando experiencias de coworking a través de tecnología innovadora.",
    "footer-contact": "Correo: support@workstation.com | Teléfono: +51 970 526 672"
  }
};